version: '3.8'

services:
  gridbnb-trader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gridbnb-trader
    restart: unless-stopped
    ports:
      - "58181:58181"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:58181"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 